name: CI Documentation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check Sphinx Documentation build minimally
        run: make docs

      - name: Check for documentation style errors
        run: make check
